### PR TITLE
Create formatter_juliaformatter.lua

### PR DESCRIPTION
**Pull request by VarLad**
Add a Julia Language formatter

### CODE REVIEW

**Comment by vincens2005** [comment]
$ARGS is not in the command string so any arguments will not work

**Comment by VarLad** [comment]
I know
Its for if in the future, I see any use of ARGS
For now, its good as it is

**Comment by VarLad** [comment]
If there isn't any other issue, I think its good enough to merge

**Comment by vincens2005** [comment]
you should put the ARGS in the string anyway, as people might want to set their own

**Comment by VarLad** [comment]
Should be good enough

**Pull request closed without merging**
